[package]
name = "incremental-topo"
version = "0.1.0"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]
description = "Data structure to maintain an incremental topological ordering over a collection of values"
repository = "https://github.com/declanvk/incremental-topo/"
readme = "README.md"

keywords = ["data-structures", "dag", "graph", "incremental", "topological"]
categories = ["algorithms", "data-structures"]

license = "MIT/Apache-2.0"


[dependencies]
failure = "~0.1.2"
failure_derive = "~0.1.2"
slab = "~0.4.1"
